### ISSUE TITLE
总是过一段时间time out 具体原因不太清楚

### ISSUE THREAD

**Issue by oldyangyagn** [BaiMeow/FishBot2#4]
没有提供更多的log

**Comment by BaiMeow** [comment]
你试试把配置文件中的超时时间调高，服务器tps不稳定会导致这个问题

**Comment by oldyangyagn** [comment]
换了个大点的鱼塘正常了,可能是之前的不规则5X5鱼塘,导致效率过慢钓不到鱼,TPS一直是20,现在没出现过这个问题了,谢谢大佬回复

柏喵Sakura ***@***.***> 于2022年1月12日周三 18:42写道：
