### ISSUE TITLE
你这go程序有问题啊

### ISSUE THREAD

**Issue by 8MiYile** [BaiMeow/FishBot2#8]
输出log
`2022/10/10 21:13:44 自动钓鱼机器人`
`2022/10/10 21:13:44 版本号：mc1.18.2`
`2022/10/10 21:13:44 验证成功`
`2022/10/10 21:13:44 exec: "powershell": executable file not found in $PATH`
`exit status 1`
运行环境 Deepin 20.7 (Golang 1.16)
描述 你这Go程序有问题啊，怎么还调用powershell的

**Comment by BaiMeow** [comment]
合理的，微软验证要调浏览跳转网页，当时借powershell随便处理了一下

**Comment by 8MiYile** [comment]
往全平台的角度来康是8合理的，建议在终端单独一行显示URL以引导打开捏

**Comment by X7A600** [comment]
```bash
运行环境 Rocklinux8 (go1.18.4 linux/amd64) 
./main
2022/12/03 10:47:43 自动钓鱼机器人
2022/12/03 10:47:43 版本号：mc1.18.2
2022/12/03 10:47:43 验证成功
2022/12/03 10:47:43 exec: "powershell": executable file not found in $PATH
```

同样问题 很不合理
